name: pytorch_integrated_cell
channels:
    - conda-forge
    - defaults
    - pytorch
dependencies:
    - python=3.6
    - pytorch=1.0.0
    - torchvision=0.2.1
    - matplotlib=2.2.2
    - numpy=1.15.0
    - pandas=0.23.4
    - pip
    - pillow=5.2.0
    - scikit-image=0.15.0
    - scipy=1.1.0
    - tifffile=0.15.0
    - h5py=2.7.1
    - tqdm=4.24.0
    - natsort=5.3.3
    - ipykernel
    - pip:
        - git+https://github.com/AllenCellModeling/aicsimage.git
        - aicsfeature=0.2.1

