ic_train_model_actk \
        --gpu_ids $1 \
        --model_type ae \
        --save_dir $PWD/bvae2D_mse \
        --lr_enc 2E-4 --lr_dec 2E-4 \
        --data_save_path $PWD/bvae2D/data_ae.pyt \
        --crit_recon integrated_cell.losses.BatchMSELoss \
        --kwargs_crit_recon '{}' \
        --network_name cvaegan2D_residual \
        --kwargs_enc '{"n_latent_dim": 512, "n_ch_target": 2, "n_ch_ref": 0, "n_classes": 0}'  \
        --kwargs_enc_optim '{"betas": [0.9, 0.999]}' \
        --kwargs_dec '{"n_latent_dim": 512, "activation_last": "softplus", "n_ch_target": 2, "n_ch_ref": 0, "n_classes": 0}' \
        --kwargs_dec_optim '{"betas": [0.9, 0.999]}' \
        --kwargs_model '{"beta": 1}' \
        --train_module bvae_ref_only \
        --imdir /allen/aics/modeling/rorydm/results/actk/2020-12-01_no_ceil_adjust/singlecellimages/ \
        --dataProvider DataProviderACTK2D \
        --kwargs_dp '{"crop_to": [160, 96], "return2D": 1, "check_files": 0, "csv_name": "manifest_mito.csv", "normalize_intensity": 1}' \
        --saveStateIter 1 --saveProgressIter 1 \
        --channels "membrane_segmentation" "nucleus_segmentation" \
        --batch_size 32  \
        --nepochs 300 \
