ic_train_model_actk \
        --gpu_ids $1 \
        --model_type ae \
        --save_dir $PWD/bvae3D_actk_ref_seg_beta_1 \
        --lr_enc 2E-4 \
        --lr_dec 2E-4 \
        --data_save_path $PWD/bvae3D_actk_ref_seg_beta_1/data_ae.pyt \
        --crit_recon integrated_cell.losses.BatchBCELoss \
        --kwargs_crit_recon '{}' \
        --network_name cvaegan3D_residual \
        --kwargs_model '{"beta_min": 1e-06, "beta_start": -1, "beta_step": 3e-05, "kld_reduction": "batch", "objective": "A"}' \
        --kwargs_enc '{"n_latent_dim": 512, "n_ch_target": 2, "n_ch_ref": 0, "n_classes": 0}'  \
        --kwargs_enc_optim '{"betas": [0.9, 0.999]}' \
        --kwargs_dec '{"n_latent_dim": 512, "activation_last": "sigmoid", "n_ch_target": 2, "n_ch_ref": 0, "n_classes": 0}' \
        --kwargs_dec_optim '{"betas": [0.9, 0.999]}' \
        --kwargs_model '{"beta": 1}' \
        --train_module bvae_ref_only \
        --imdir /allen/aics/modeling/jacksonb/results/actk/2020-09-03/singlecellimages/ \
        --dataProvider RefDataProviderACTKSeg \
        --kwargs_dp '{"crop_to": [160, 96, 64], "normalize_intensity": "max", "return2D": 0, "check_files": 0, "csv_name": "manifest.csv"}' \
        --saveStateIter 1 \
        --saveProgressIter 1 \
        --channels "membrane_segmentation" "structure" "nucleus_segmentation" \
        --batch_size 32  \
        --nepochs 300 \
