ic_train_model \
        --gpu_ids $1 \
        --model_type ae \
        --save_dir $PWD/cbvae2D \
        --lr_enc 2E-4 --lr_dec 2E-4 \
        --data_save_path $PWD/cbvae2D/data.pyt \
        --crit_recon integrated_cell.losses.BatchMSELoss \
        --kwargs_crit_recon '{}' \
        --network_name cvaegan2D_residual \
        --kwargs_enc '{"n_latent_dim": 512, "n_ch_target": 1, "n_ch_ref": 2, "n_classes": 24}'  \
        --kwargs_enc_optim '{"betas": [0.9, 0.999]}' \
        --kwargs_dec '{"n_latent_dim": 512, "activation_last": "softplus", "n_ch_target": 1, "n_ch_ref": 2, "n_classes": 24}' \
        --kwargs_dec_optim '{"betas": [0.9, 0.999]}' \
        --kwargs_model '{"beta": 1}' \
        --train_module cbvae2_target \
        --imdir ../../data/ \
        --dataProvider TargetDataProvider \
        --kwargs_dp '{"crop_to": [160, 96], "return2D": 1, "check_files": 0, "csv_name": "metadata.csv"}' \
        --saveStateIter 1 --saveProgressIter 1 \
        --channels_pt1 0 1 2 \
        --batch_size 32  \
        --nepochs 300 \
