name: Build Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        docker build -t aics/pytorch_integrated_cell -f Dockerfile .
    - name: Run tests
      run: |
        docker run aics/pytorch_integrated_cell pytest --cov-report xml --cov=integrated_cell integrated_cell/tests/
        docker run aics/pytorch_integrated_cell codecov -t ${{ secrets.CODECOV_TOKEN }}
