name: Build Docker

 on: [push, pull_request]

 jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        docker build -t aics/pytorch_integrated_cell -f Dockerfile .
